### ISSUE TITLE
App no longer be available on Play Store

### ISSUE THREAD

**Issue by neonpixii** [adrielcafe/Chroma#3]
Hello

It appears that Chroma is no longer available on the play store. This is a shame because its my favorite tuner app and also the only good chromatic tuner application available.

Is there any idea why this happened and when it will return to the Play Store?

**Comment by adrielcafe** [comment]
Hi @neonpixii ,

Chroma is back on the Play Store, sorry for the inconvenience and thanks for your support!

**Comment by Poussinou** [comment]
Hi @adrielcafe 

Would it be possible to add a release signed apk to your [last release](https://github.com/adrielcafe/chroma/releases/tag/1.1.5) so that people without Play Store can download it?
